# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          
     # INSTALAR AS DEPENDÊNCIAS NPM/YARN
      - name: Install dependencies
        run: yarn
        
     # EXECUTAR A BUILD
      - name: Run build
        run: yarn build
        
      # COPIAR PASTA "dist" PARA DENTRO DO SERVIDOR DE PRODUCAO
      - name: Copy dist to server production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
      

     # SUBSTITUIR O CÓDIGO EXISTENTE NA PASTA "dist" PELO NOVO CÓDIGO     
     # EXECUTAR YARN DENTRO DO SERVIDOR DE PRODUÇÃO
     # EXECUTAR AS MIGRATIONS DO TYPEORM
     # RESTART NODEJS
